## DISCLAIMER

THIS CODE AND RELATED DOCUMENTS ARE PROVIDED ON AN "AS IS" BASIS. ARCHIMEDES SOLUTIONS, ITS OFFICERS, EMPLOYEES, AND AFFILIATES (COLLECTIVELY "ARCHIMEDES SOLUTIONS") MAKE NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THESE INSTRUCTIONS, RELATED CODE, BUILD SCRIPTS, OR ANY THIRD PARTY PACKAGES.
YOU EXPRESSLY AGREE THAT YOUR USE OF THIS CODE IS AT YOUR SOLE RISK.
ARCHIMEDES SOLUTIONS WILL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND ARISING FROM THE USE OF THIS CODE INCLUDING, BUT NOT LIMITED TO, DIRECT, INDIRECT, INCIDENTAL, PUNITIVE, AND CONSEQUENTIAL DAMAGES.

## Creative Commons Attribution Non Commercial No Derivatives 4.0 International

Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International Public License

see: https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode 

Copyright (c) 2023 Archimedes Solutions

