apiVersion: apps/v1
kind: Deployment
metadata:
  name: groot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: groot-eth-nodes
  template:
    metadata:
      labels:
        app: groot-eth-nodes
    spec:
      hostNetwork: true
      containers:
      - name: eth-node-1
        image: 240910251918.dkr.ecr.us-west-2.amazonaws.com/groot:arch-production-node
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "2"
            memory: "16Gi"
          limits:
            cpu: "4"
            memory: "24Gi"
        envFrom:
        - configMapRef:
            name: demoapp-config
        env:
        - name: ALCHEMY_API_KEY
          valueFrom:
            secretKeyRef:
              name: alchemy-api-key
              key: ALCHEMY_API_KEY
        - name: HARDHAT_PORT
          valueFrom:
            configMapKeyRef:
              name: demoapp-config
              key: MAIN_LOCAL_NODE_PORT
        - name: NEW_RELIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic-api-key
              key: NEW_RELIC_API_KEY
        ports:
        - containerPort: 8545
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - >
              curl -X POST
              -H "Content-Type: application/json"
              --data '{"method":"eth_blockNumber","params":[],"id":1,"jsonrpc":"2.0"}'
              http://localhost:8545
          initialDelaySeconds: 60
          periodSeconds: 3
          failureThreshold: 30
        
      - name: eth-node-2
        image: 240910251918.dkr.ecr.us-west-2.amazonaws.com/groot:arch-production-node
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "2"
            memory: "16Gi"
          limits:
            cpu: "4"
            memory: "24Gi"
        envFrom:
        - configMapRef:
            name: demoapp-config
        env:
        - name: ALCHEMY_API_KEY
          valueFrom:
            secretKeyRef:
              name: alchemy-api-key
              key: ALCHEMY_API_KEY
        - name: HARDHAT_PORT
          valueFrom:
            configMapKeyRef:
              name: demoapp-config
              key: ALT_LOCAL_NODE_PORT
        - name: NEW_RELIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic-api-key
              key: NEW_RELIC_API_KEY
        ports:
        - containerPort: 18545
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - >
              curl -X POST
              -H "Content-Type: application/json"
              --data '{"method":"eth_blockNumber","params":[],"id":1,"jsonrpc":"2.0"}'
              http://localhost:18545
          initialDelaySeconds: 60
          periodSeconds: 3
          failureThreshold: 30

      - name: groot-container
        image: 240910251918.dkr.ecr.us-west-2.amazonaws.com/groot:groot-container
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "2"
            memory: "8Gi"
          limits:
            cpu: "4"
            memory: "24Gi"
        envFrom:
        - configMapRef:
            name: demoapp-config
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-access-key-id
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret-access-key
              key: AWS_SECRET_ACCESS_KEY
        - name: MAIN_LOCAL_NODE_URL
          value: "http://localhost"
        - name: MAIN_LOCAL_NODE_PORT
          valueFrom:
            configMapKeyRef:
              name: demoapp-config
              key: MAIN_LOCAL_NODE_PORT
        - name: ALT_LOCAL_NODE_URL
          value: "http://localhost"
        - name: ALT_LOCAL_NODE_PORT
          valueFrom:
            configMapKeyRef:
              name: demoapp-config
              key: ALT_LOCAL_NODE_PORT
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: demoapp-config
              key: ENVIRONMENT
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: demoapp-config
              key: AWS_REGION
        - name: NEW_RELIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic-api-key
              key: NEW_RELIC_API_KEY
      restartPolicy: Always