apiVersion: apps/v1
kind: Deployment
metadata:
  name: groot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: groot
  template:
    metadata:
      labels:
        app: groot
    spec:
      containers:
      - name: groot-container
        image: 240910251918.dkr.ecr.us-west-1.amazonaws.com/groot:groot-container
        imagePullPolicy: Always
        env:
        - name: MAIN_LOCAL_NODE_PORT
          value: "8545"
        - name: ALT_LOCAL_NODE_PORT
          value: "18545"
      - name: eth-node-1
        image: 240910251918.dkr.ecr.us-west-1.amazonaws.com/groot:arch-production-node
        imagePullPolicy: Always
        env:
        - name: HARDHAT_PORT
          value: "8545"
        ports:
        - containerPort: 8545
      - name: eth-node-2
        image: 240910251918.dkr.ecr.us-west-1.amazonaws.com/groot:arch-production-node
        imagePullPolicy: Always
        env:
        - name: HARDHAT_PORT
          value: "18545"
        ports:
        - containerPort: 18545
      restartPolicy: Always