apiVersion: batch/v1
kind: CronJob
metadata:
  name: groot-cronjob
spec:
  schedule: "*/1 * * * *"   # Run every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: groot-container
            image: groot-container
            imagePullPolicy: Always
            envFrom:
            - configMapRef:
                name: demoapp-config
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-access-key-id
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret-access-key
                  key: AWS_SECRET_ACCESS_KEY
          restartPolicy: OnFailure