apiVersion: batch/v1
kind: CronJob
metadata:
  name: groot-cronjob
spec:
  schedule: "*/1 * * * *"   # Run every minute
  jobTemplate:
    spec:
      template:
        spec:
          hostNetwork: false
          containers:
          - name: groot-container
            image: docker.io/library/groot-container:latest
            imagePullPolicy: IfNotPresent
            envFrom:
            - configMapRef:
                name: demoapp-config
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-access-key-id
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret-access-key
                  key: AWS_SECRET_ACCESS_KEY
            - name: MAIN_LOCAL_NODE_URL
              value: "http://groot-service"
            - name: MAIN_LOCAL_NODE_PORT
              valueFrom:
                configMapKeyRef:
                  name: demoapp-config
                  key: MAIN_LOCAL_NODE_PORT
            - name: ALT_LOCAL_NODE_URL
              value: "http://groot-service"
            - name: ALT_LOCAL_NODE_PORT
              valueFrom:
                configMapKeyRef:
                  name: demoapp-config
                  key: ALT_LOCAL_NODE_PORT
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: demoapp-config
                  key: ENVIRONMENT
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: demoapp-config
                  key: AWS_REGION
          restartPolicy: OnFailure



          