apiVersion: apps/v1
kind: Deployment
metadata:
  name: groot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: groot-eth-nodes
  template:
    metadata:
      labels:
        app: groot-eth-nodes
    spec:
      containers:
      - name: eth-node-1
        image: arch-production-node
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: demoapp-config
        env:
        - name: ALCHEMY_API_KEY
          valueFrom:
            secretKeyRef:
              name: alchemy-api-key
              key: ALCHEMY_API_KEY
        ports:
        - containerPort: 8545
      - name: eth-node-2
        image: arch-production-node
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: demoapp-config
        env:
        - name: ALCHEMY_API_KEY
          valueFrom:
            secretKeyRef:
              name: alchemy-api-key
              key: ALCHEMY_API_KEY
        ports:
        - containerPort: 18545
      restartPolicy: Always