apiVersion: v1
kind: Service
metadata:
  name: groot-service
spec:
  selector:
    app: groot-eth-nodes
  ports:
  - name: eth-node-1
    port: 8545
    targetPort: 8545
  - name: eth-node-2
    port: 18545
    targetPort: 18545