# eksctl create cluster  -f scripts/k8s/cluster_creation/cluster-creation.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: groot-demo-app
  region: us-west-2
  version: '1.29'

cloudWatch:
  clusterLogging:
    enableTypes: ["audit", "authenticator", "controllerManager"]
    logRetentionInDays: 60

