# eksctl create cluster  -f scripts/k8s/cluster_creation/config.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: groot-stable-app
  region: us-west-1
  version: '1.29'

cloudWatch:
  clusterLogging:
    enableTypes: ["audit", "authenticator", "controllerManager"]
    logRetentionInDays: 60

