const TYPES = {
  ILoggerAll: 'ILoggerAll',
  ILoggerConsole: 'ILoggerConsole',
  IConfigServiceAWS: 'IConfigServiceAWS',
  Environment: 'Environment',
  Region: 'Region',
  MainLocalNodeURI: 'MainLocalNodeURI',
  AltLocalNodeURI: 'AltLocalNodeURI',
  BlockchainNodeLocalMain: 'BlockchainNodeLocalMain',
  BlockchainNodeLocalAlt: 'BlockchainNodeLocalAlt',
  Groot: 'Groot',
  ServiceName: 'ServiceName',
  IBlockchainReader: 'IBlockchainReader',
  AlchemyNodeLabel: 'AlchemyNodeLabel',
  InfuraNodeLabel: 'InfuraNodeLabel',
  IBlockchainNodeHealthMonitor: 'IBlockchainNodeHealthMonitor',
  IHostNameProvider: 'IHostNameProvider',
  ISignalHeartbeat: 'ISignalHeartbeat',
  ISignalCriticalFailure: 'ISignalCriticalFailure',
  IHealthMonitor: 'IHealthMonitor',
  MetricNamespaceHeartBeat: 'MetricNamespaceHeartBeat',
  MetricNamespaceCriticalFailure: 'MetricNamespaceCriticalFailure',
  IAbiStorageDynamoDB: 'IAbiStorageDynamoDB',
  IAbiFetcherEtherScan: 'IAbiFetcherEtherScan',
  IAbiRepo: 'IAbiRepo',
  IFactoryRule: 'IFactoryRule',
  IRuleEngine: 'IRuleEngine',
  PGClient: 'PGClient',
  PostgreTxQueue: 'PostgreTxQueue',
  ITransactionQueuer: 'ITransactionQueuer',
  PostgreDataSource: 'PostgreDataSource',
};

export { TYPES };
