const TYPES = {
  ILoggerAll: 'ILoggerAll',
  ILoggerConsole: 'ILoggerConsole',
  ConfigServiceAWS: 'ConfigServiceAWS',
  DBService: 'DBService',
  Environment: 'Environment',
  Region: 'Region',
  MainLocalNodeURI: 'MainLocalNodeURI',
  AltLocalNodeURI: 'AltLocalNodeURI',
  BlockchainNodeLocalMain: 'BlockchainNodeLocalMain',
  BlockchainNodeLocalAlt: 'BlockchainNodeLocalAlt',
  Groot: 'Groot',
  ServiceName: 'ServiceName',
  IBlockchainReader: 'IBlockchainReader',
  AlchemyNodeLabel: 'AlchemyNodeLabel',
  InfuraNodeLabel: 'InfuraNodeLabel',
  IBlockchainNodeHealthMonitor: 'IBlockchainNodeHealthMonitor',
  IHostNameProvider: 'IHostNameProvider',
  ISignalHeartbeat: 'ISignalHeartbeat',
  ISignalCriticalFailure: 'ISignalCriticalFailure',
  IHealthMonitor: 'IHealthMonitor',
  MetricNamespaceHeartBeat: 'MetricNamespaceHeartBeat',
  MetricNamespaceCriticalFailure: 'MetricNamespaceCriticalFailure',
  IAbiStorageDynamoDB: 'IAbiStorageDynamoDB',
  IAbiFetcherEtherScan: 'IAbiFetcherEtherScan',
  IAbiRepo: 'IAbiRepo',
  FactoryRule: 'FactoryRule',
  RuleEngine: 'RuleEngine',
  PostgreTxQueue: 'PostgreTxQueue',
  ITransactionQueuer: 'ITransactionQueuer',
  TransactionsDataSource: 'TransactionsDataSource',
  PostgreDataSource: 'PostgreDataSource',
  PositionLedgerContract: 'PositionLedgerContract',
};

export {TYPES};
